version: '3.2'

services:
    mc:
        image: itzg/minecraft-server
        volumes:
            - ~/crafty1/data:/data
        environment:
            EULA: "true"
            MEMORY: "4G"
            ENFORCE_WHITELIST: "true"
            WHITELIST: "satetheus"
            WHITELIST: "nightcraler123"
            OPS: "satetheus"
            TYPE: CURSEFORGE
            CF_SERVER_MOD: SevTech-Ages_Server_3.1.5.zip
        ports:
            - 25565:25565

        tty: true

        stdin_open: true

        restart: always

